### ISSUE TITLE
Filter out city matching contributions from map and bracketed contribution table

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/openelections#1031]
### What

City matching contributions should not show as either large circles on the map, or as "mega" contributions. In `publicData.js`, we should filter for them so that they are not displayed.

### Why

We should filter for these contributions so that they can be appropriately accounted for in the data. See  #1020 #1023 for more detail.

### When
By Thursday, January 30, 2020

**Comment by jaronheard** [comment]
In order to implement this feature, we need to know what unique attributes we can filter for to capture city matching contributions.

@susanmottet, you had manually adjusted the matching contributions that were in the system. What unique attributes or combination of attributes only applies to these matching contributions so that we can filter them out?

**Comment by susanmottet** [comment]
What unique attributes or combination of attributes only applies to these matching contributions so that we can filter them out?

They are all labeled "Public Matching Contribution" under the OAE Type field.  
y should all say "1221 SW 4th Avenue" in the address label, but, of course, people might express that differently (Avenue, Ave, add or don't add Suite 120, etc.).  
They should all say either "City of Portland" or "Treasurer of the City of Portland" in the Name field, but that also get expressed differently in small ways. 

Those are the only things that make the public matching contributions unique that I can identify.
