### ISSUE TITLE
Add a validation mask for amount, email and phone number on contributions form

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#589]
![Open_Elections](https://user-images.githubusercontent.com/99731/62793182-ce88cf80-ba85-11e9-8ec0-823e40068511.png)

Please add a validation mask for amount, phone number and email address

**Comment by kdv24** [comment]
After spending some time researching this, it seems like the best method to handle these validation masks is to use one of the following libraries:
- [react-input-mask](https://github.com/sanniassin/react-input-mask): probably the most popular
- [text-mask](https://github.com/text-mask/text-mask/): has addons for what we need
- [react-masked-field](https://github.com/Gusto/react-masked-field): published 14 days ago and has > 6500 weekly downloads 🤷‍♀ 

However, I'm running into the same error regardless of the library I try. In all cases I get the following error: `Attempted import error: 'matchPath' is not exported from 'react-router'.` Researching this, I found something saying "The error occurs when you have mixed versions of react-router and react-router-dom installed." 

I feel like I'm headed down a rabbit hole though.  Am I making this more complicated than it needs to be? 

Also, there's a bit more logic to be written because the type of validation for the `Contact Type` field will be different depending on the answer of `email` or the others. 

@jaronheard or @mscotto or @jasonvalenzuela I'd love thoughts...

**Comment by jaronheard** [comment]
Material uses react-text-mask and react-number-format in its [example](https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries), and has another mention of react-stripe-field.

As far as the react router issue — sounds like a dependency issue, in some way. Can you post your results of `yarn why react-router` and `yarn why react-router-dom`?

**Comment by kdv24** [comment]
@jaronheard 
`yarn why react-router` gives:
``` 
yarn why v1.15.2
[1/4] 🤔  Why do we have the module "react-router"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-router@5.0.1"
info Reasons this module exists
   - "react-router-dom" depends on it
   - Hoisted from "react-router-dom#react-router"
info Disk size without dependencies: "316KB"
info Disk size with unique dependencies: "1.7MB"
info Disk size with transitive dependencies: "1.89MB"
info Number of shared dependencies: 15
=> Found "@hackoregon/component-library#react-router@3.2.3"
info This module exists because "@hackoregon#component-library" depends on it.
info Disk size without dependencies: "812KB"
info Disk size with unique dependencies: "1.48MB"
info Disk size with transitive dependencies: "15.68MB"
info Number of shared dependencies: 21
✨  Done in 3.14s.
```

And `yarn why react-router-dom` gives:
```
yarn why v1.15.2
[1/4] 🤔  Why do we have the module "react-router-dom"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-router-dom@5.0.1"
info Has been hoisted to "react-router-dom"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "384KB"
info Disk size with unique dependencies: "1.86MB"
info Disk size with transitive dependencies: "2.27MB"
info Number of shared dependencies: 15
✨  Done in 1.29s.
```
```

**Comment by jaronheard** [comment]
Ah hah! This is an issue with our component library dependencies.

I should be able to do a quick fix and publish. Can you provide the version of @hackoregon/component-library depended on?

**Comment by kdv24** [comment]
Sorry @jaronheard , I didn't see this till now.  It looks like the version is `    "@hackoregon/component-library": "6.9.0"`

**Comment by kdv24** [comment]
So, just for the sake of documenting here - the issue was cleared up by removing the package-lock.json file causing conflicts with yarn.

Based on Material UI using [text-mask](https://github.com/text-mask/text-mask/) in the their example and my research finding that one has the add-ons we need.  I'll move forward now with trying to make that work.

**Comment by kdv24** [comment]
Current Status on this issue:
- Value is there in the field:
<img width="1387" alt="Screen Shot 2019-08-15 at 12 28 16 PM" src="https://user-images.githubusercontent.com/6107653/63130333-eb823e80-bf6e-11e9-8234-f8fd2ddc1483.png">

- but value isn't in formik:
<img width="757" alt="Screen Shot 2019-08-15 at 12 28 50 PM" src="https://user-images.githubusercontent.com/6107653/63130495-83802800-bf6f-11e9-8e72-d21503d02ae2.png">

- and disappears onBlur:
<img width="569" alt="Screen Shot 2019-08-15 at 12 28 30 PM" src="https://user-images.githubusercontent.com/6107653/63130390-1bc9dd00-bf6f-11e9-8316-a3d6d75fd667.png">

- formik error on submit:
<img width="1178" alt="Screen Shot 2019-08-15 at 12 33 41 PM" src="https://user-images.githubusercontent.com/6107653/63130883-bd9df980-bf70-11e9-88c8-59560cd78abd.png">
