### ISSUE TITLE
Create an activity feed widget

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#610]
Create a new activity feed widget. The activity feed pulls activity items for a campaign, government, contribution, or expenditure. It can also take a per page and page parameter.

- [x] Add an h3 header 'Activity Stream'
- [x] Each activity should have a header title of created at timestamp and type (User, Permission, Contribution, Expenditure, Expenditure Comment, Contribution Comment), (05/19/2019 @5:55pm Contribution Activity), (05/19/2019 @5:55pm Contribution Comment Activity), (05/19/2019 @5:55pm User Permission Activity)
- [x] If the activity stream is over 25 entries, add pagination to the bottom of the widget
- [x] The activity widget redux connector should take ownProps of contributionId, governmentId, campaignId or expenditureId, and on componentDidMount, use the get activities duck
- [x] Add to the government dashboard (governmentId set)
- [x] Add to the campaign dashboard (campaignId set)
- [x] Add to the expenditure detail page expenditures/:id
- [x] Add to the contribution detail page contributions/:id
![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837128-a71a3a00-bc20-11e9-8bb3-bbc04045db67.png)

**Comment by kdv24** [comment]
This has already been started on `activity_stream` branch

**Comment by kdv24** [comment]
Big things remaining on this ticket:

- [x] activities are showing on _all_ contributions/expenditures (depending on which they are) instead of only ones they belong to -FIXED
- [ ] date is not formatted correctly on activity stream view
- [x] pagination
- [x] expenditures activity list is not automatically refreshing the way contributions does with new comment
- [x] campaigns dashboard activity stream not added 
- [x] gov dashboard activity stream not added at all yet (where does that go?)
-- added now, but not populating correctly (and loses all data on refresh)
