### ISSUE TITLE
API: Add total number to all results queries for contributions and expenditures

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#733]
Please add totals to contributions and expenditures

**Comment by jaronheard** [comment]
Additional notes:

Andrew Erickson Sep 2nd at 9:42 PM
I’m working on https://github.com/hackoregon/openelections/issues/678 adding custom pagination to our contributions table. It seems like we would want to know a total # of matches for a specific request when using pagination. According to the swagger docs, it looks like it responds with an array of objects instead of something like this:
{
  totalMatches: 150,
  page: 0,
  perPage: 25,
  items: [
    {...},
    {...},
  ]
}
I may be thinking about it wrong, but the UI will be pretty useless if it seems like we have unlimited hits and can’t show 25 out of 50 or something similar. I’m thinking we hold off on this until the API is updated or I’m totally missing something (more likely possibility).

**Comment by danmelton** [comment]
@jaronheard @andrewbiang888 the api and app have been updated with a total count for contributions and expenditures
