### ISSUE TITLE
Need to be able to add state of foreign employer in contributions

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#861]
An American who works abroad is permitted to make contributions to campaigns. However, when we collect city and state of employer, the only options for states are within the US.  Can we add an additional option to allow campaigns to deal with these contributions? 

One idea is to just add one more option: "foreign." Then they could write the city and state in the city field and select foreign for state. For example... City: Auckland, NZ  | State: Foreign.  Alternatively, we could allow them to write in whatever text they like instead of selecting a state. There also may be other solutions. 

This is a rare scenario. 

- [ ] API: Add type forgienEmployment to employment types, add employerCountry to contributions
- [x] Frontend: Add type forgienEmployment to employment types dropdown, add employerCountry to form fields, default country to USA

**Comment by kdv24** [comment]
@danmelton @susanmottet do we also need to show the Occupation Letter field in this scenario?  


And, because foreign addresses may not have a state, do we want to handle it by adding 'foreign' like Susan suggested, or should we just not show the state field when 'foreign' is selected.  It might be easiest to just display the `country` field instead of the `state` field when someone selects 'foreign employed'.  I just want to be clear how to plan for the absence of a state.

**Comment by kdv24** [comment]
started frontend work #892 
will wait for answers before proceeding
