### ISSUE TITLE
Design changes for individual expense page

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#925]
When looking at an individual expense, one of the most important pieces of information is the type of expense it is. I'm not sure if we are displaying this information but I think we were before, and it would be helpful if we did. This is applicable to both Campaign and City UI.

**Comment by kdv24** [comment]
@amysantee just to clarify, do you mean type ('expense', 'other', 'other disbursement') or subtype ('accounts payable', 'cash expenditure', 'personal expenditure', etc)?

**Comment by danmelton** [comment]
@kdv24 can we add both to the UI?

**Comment by kdv24** [comment]
yep - starting it now

**Comment by amysantee** [comment]
more like, the different types of stuff they can spend money on. like, advertising, etc., etc. I don't have the complete list but Susan can tell you the different types. I think another one might be consulting? not totally sure.

**Comment by amysantee** [comment]
both to the UI would be good

**Comment by kdv24** [comment]
So @amysantee advertising, etc is a purpose type and only is required if the subtype is miscellaneous other reimbursement.  I just want to clarify that's still correct.  It just means only some records will have a purpose type listed.

Also, I'm not really sure which "both" you mean, since we're now talking about three separate fields.  I just want to make sure I do what's wanted!  😄 

Let me know if any of my questions/responses don't make sense!

**Comment by amysantee** [comment]
Dan made a comment about "both" so that's what I was referring to.

For purpose type, that's a good question. I'm not totally sure. I will ask Elizbeth.

**Comment by kdv24** [comment]
yeah, "both" made sense when there were only two fields, but now I'm not sure which of the three are most useful to show.  I'll wait to here back and see if it makes more sense to me then.

**Comment by kdv24** [comment]
closed per conversation with @amysantee - no longer needed
