### ISSUE TITLE
Date is changing on submit

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#946]
When I submit a contribution, the date is getting update/changed in the api
![Open_Elections](https://user-images.githubusercontent.com/99731/66615902-748ab000-eb83-11e9-98ef-50b879ee814b.png)

**Comment by danmelton** [comment]
this is also happening on expenses.

**Comment by punkael** [comment]
I believe this only happens with seed data. This is because the seed data is not an exact day as in 00:00:00 or is not an exact day in our timezone. As a fix we can check formik for dirty fields so that the date update only happens when and if other fields are also modified.  A pull for this is here #955

**Comment by danmelton** [comment]
we're getting reports that this is happening in production
